language: android

jdk:
- oraclejdk8

env:
  global:
    - ANDROID_TARGET=android-19
    - ANDROID_ABI=armeabi-v7a

android:
  components:
  - tools
  - tools
  - platform-tools
  - build-tools-26.0.2
  - android-19
  - android-25
  - android-26
  - extra-google-google_play_services
  - extra-android-m2repository
  - extra-google-m2repository
  - sys-img-armeabi-v7a-android-19
  licenses:
  - '.+'

branches:
  except:
    - gh-pages

notifications:
  email: false

before_script:
  # Create and start an emulator for instrumentation tests.
  - android list targets
  - echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI
  - emulator -avd test -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell setprop dalvik.vm.dexopt-flags v=n,o=v
  - adb shell input keyevent 82

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle
    - $HOME/.android/build-cache

before_install:
  - chmod +x gradlew
  - mkdir "$ANDROID_HOME/licenses" || true
  - echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
  - echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"
  - echo yes | sdkmanager "extras;m2repository;com;android;support;constraint;constraint-layout;1.0.2"
  - echo yes | sdkmanager "extras;m2repository;com;android;support;constraint;constraint-layout-solver;1.0.2"
  - yes | sdkmanager "platforms;android-27"

script:
  - ./gradlew build jacocoTestReport assembleAndroidTest connectedCheck

after_success:
  - bash <(curl -s https://codecov.io/bash)
